// <auto-generated />
namespace ThursdayAfternoon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class Presentation_Add_Description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Presentation_Add_Description));
        
        string IMigrationMetadata.Id
        {
            get { return "201307301513089_Presentation_Add_Description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
