// <auto-generated />
namespace ThursdayAfternoon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class User_Add_NameDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(User_Add_NameDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201308051439321_User_Add_NameDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
